##############################################################
### Find all jobs
GET http://localhost:4000/jobs?date=2026-05-24
### Find job by ID
GET http://localhost:4000/jobs/cmpj8xdi100001kn8a8qyh3f3

### Create a new job
POST http://localhost:4000/jobs
Content-Type: application/json

{
  "title": "Software Engineer",
  "description": "We are looking for a skilled software engineer to join our team.",
  "status": "ystus"
}

### Update a job
PATCH http://localhost:4000/jobs/cmph7jzv8000001qwn3laltv1
Content-Type: application/json  

{
    "title": "Update job",
    "description": "jfs f skfj sfj s sdfjdsf ds ksfjdslf s fkdsjf",
    "status": "open",
    "address": "jdsjfkdsf"
  }

##############################################################
### Find all customers
GET http://localhost:4000/customers
### Find customer by ID
GET http://localhost:4000/customers/cmpo82h8pfdd00006bpexhp1iqpv

### Create a new customer
POST http://localhost:4000/customers
Content-Type: application/json

{
  "name": "Adam Sandler",
  "email": "adem-senadler@example.de",
  "phone": "+49 170 853583",
  "address": "Konigstrasse 31, 80331 Stuttgart"
}

### Update a customer
PATCH http://localhost:4000/customers/cmpo82h8p00006bpexhp1iqpv
Content-Type: application/json

{
  "name": "Updated Adam Sandler",
  "email": "adem-senadler@example.de"
}

### Delete a customer
DELETE http://localhost:4000/customers/cmpo6nuhi000037peb0864odc

### Search customers
GET http://localhost:4000/customers?search=Hans
