### Find all jobs
GET http://localhost:4000/jobs

### Find job by ID
GET http://localhost:4000/jobs/cmpj8xdi100001kn8a8qyh3f3

### Create a new job
POST http://localhost:4000/jobs
Content-Type: application/json

{
  "title": "Software Engineer",
  "description": "We are looking for a skilled software engineer to join our team.",
  "status": "ystus"
}

### Update a job
PATCH http://localhost:4000/jobs/cmph7jzv8000001qwn3laltv1
Content-Type: application/json  

{
    "title": "Update job",
    "description": "jfs f skfj sfj s sdfjdsf ds ksfjdslf s fkdsjf",
    "status": "open",
    "address": "jdsjfkdsf"
  }