version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - ai-service
      - postgres
      - redis
    environment:
      AI_SERVICE_URL: http://ai-service:8000
      DATABASE_URL: postgresql://admin:admin@postgres:5432/handwerk
      REDIS_URL: redis://redis:6379

  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kraftmeister
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
