version: "3.9"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000

  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    command: npm run start:dev
    container_name: api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - ai-service
      - postgres
      - redis
    environment:
      AI_SERVICE_URL: http://ai-service:8000
      DATABASE_URL: postgresql://admin:admin@postgres:5432/kraftmeister
      REDIS_URL: redis://redis:6379

  ai-service:
    build: ./ai-service
    volumes:
      - ./ai-service:/app
    container_name: ai-service
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kraftmeister
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
