services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    env_file: .env.dev

  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    container_name: api-gateway
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-service:
        condition: service_started
      minio:
        condition: service_healthy
    env_file: .env.dev

  ai-service:
    build: ./ai-service
    volumes:
      - ./ai-service:/app
    container_name: ai-service
    ports:
      - "8000:8000"
    env_file: .env.dev

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kraftmeister"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: always
    env_file: .env.dev
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: always
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.dev

volumes:
  postgres_data:
  minio_data:
